nelmio_api_doc:
    documentation:
        info:
            title: ART-GE
            description: Retourne les données sur les résultats des réponses aux formulaires
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - /api/resultats
