hosts:
    production:
        port: ENC[AES256_GCM,data:aA0=,iv:hsy8kJ4yrqE61435I62KiIC6edQ/3cmFdP6QbV36W6c=,tag:17CrC55RXlXVLN994eXzWw==,type:int]
        identity_file: ENC[AES256_GCM,data:4f6+AtKlkjH1Wl1TJVCH5khrsQ==,iv:CZB6v1J4LuEHHN9crrnyERmwhgntl06Fx8kAfzGBbR4=,tag:P27nvoBqt6jDf4KfB/v4nw==,type:str]
        forward_agent: ENC[AES256_GCM,data:xAs99A==,iv:DrANkWD44wPXFoYz5fKBiJfG+SK07x6VmQ/xtq1sqfE=,tag:QedKSX93gZKxBGzSObjlWg==,type:bool]
        keep_releases: ENC[AES256_GCM,data:Mw==,iv:nBsfJ3nI9oJu6Vd81h8Jw6cLOke3rYlRtovyJkZsc8I=,tag:8G+WdieAshXbTudaZ+9smA==,type:int]
        git_ssh_command: ENC[AES256_GCM,data:50e0MnV2+rMwfZUsQMqPxyOXhanToLz3ghL9ctMJzIfoYtfqCeR0M/GzddF3m7VP+E32GUfl1iqT5sdrTf7h,iv:4qV22gwx6PZ6cV7EyjMMArNGVPvsk1ylX4RMBMM6aQc=,tag:btDZaB1d5YGUZnfAvz4lNg==,type:str]
        ssh_arguments:
            - ENC[AES256_GCM,data:Nvyu89IgNTdsKT7mJIT1cl0iFhdw,iv:saFhCNucBTkdT6JuK7/DOpFNSx/AOEV9JSgLXB5KSLA=,tag:zbk3Q0gMKTFR0LXCoEdTDQ==,type:str]
            - ENC[AES256_GCM,data:nkApOTyPYftGFSXJyAmKPf+yeH3gjLykuasINYOQzg==,iv:O/6S5kh2DbaE5KnqMnezYN544sTT6mSHkzy6xve34sY=,tag:1ZDXdC4bNbJ65NaVZ8wl9Q==,type:str]
            - ENC[AES256_GCM,data:fp2o88N837min3vnIqLHOo2DiKoPEMkGzbul,iv:/aowkle/HyR8VLDcSGsSc6UbzxzHL7c+RkdyOjBkP4I=,tag:PZXlpkONGWXM7FHjn3BW3w==,type:str]
        bin/php: ENC[AES256_GCM,data:Q6DdBYkRd7O7ls99za3wgw==,iv:Ho5x36hRq7zAZ0AvEN+jW9lOO6C6C82XcUfCwOeST0U=,tag:Mb1rYTGUQYPUm50bG0RCYQ==,type:str]
        hostname: ENC[AES256_GCM,data:yTzKLaWhiGNz7cK4CInC2cQZfpucfm1ebA==,iv:2LzWVJSXlwFhtwwORDuMBsPlVlEiy2zLLJ96QPdxFNg=,tag:HTmcSRsMtIY97iNk9Lj8UA==,type:str]
        remote_user: ENC[AES256_GCM,data:x1QSp72sEUc893yg,iv:MZZCX720u8FLdzjARWN/PG/4hxEls4riGJTNNiLOLuQ=,tag:V8r4Ey+Psb9gwoYH/2tkKQ==,type:str]
        deploy_path: ENC[AES256_GCM,data:pHBsYI1TU2K3ekuvFY7oBwPpFhLbQlC0925Q6Xg4kIioqOs=,iv:hBeMQuJ4g9vS8V6Pv/4yKga/4HnjtI9zscDMlq8vrgw=,tag:Ms0uX8r+X9eKc6cVXpRccQ==,type:str]
        database_url: ENC[AES256_GCM,data:zx7SFMFCRbMAPqciREhdlmxU1n2wMReOGjsUv/KsUQAo6QoLHB/FtIRC9vUm3ppULTT+iP4EymYNkh6tRoz+gUsYXOU5bTgR3mw1TnBXF1YitRNU/BMpOs8XqfqhR46CifAfKbO2/tswNWS+ndUaPi5YcTEA7o4sVik=,iv:B2WsSERsjpW9zP4QqtpIA2TwdbjNdn1FJPqKPweQmsA=,tag:kSG5/NRlN27TsVSk6cl82Q==,type:str]
        branch: ENC[AES256_GCM,data:2HNnAg==,iv:RhkN/Ak6d9isrTkzR7kkytelFsDNqp6TGmD1OxNydGQ=,tag:D9j6NgdMYjz/wGBil/0OcQ==,type:str]
        app_env: ENC[AES256_GCM,data:Gecv+CuVkg==,iv:OrGb4vBgMVczVoaW1TNBJR7TqOkb5Yzq3S1g7Tg6hpQ=,tag:UQ6QXOAqglJsyYXoHObRXg==,type:str]
        brevo_user: ENC[AES256_GCM,data:MDIXwZZokuGkWl9eg2VuEK6/oNryD5p70EA=,iv:FUbm16KNEOi6Nuu3c0C5AhUxL6hliGICYcdVqF87GMY=,tag:mEypImKxbUhZWhKdqcs2/Q==,type:str]
        brevo_pass: ENC[AES256_GCM,data:5A2jw/4yA0FuZVtLjTmu8WJI2O7KFHBwr4jDw3LRjPIpMOvEH0m4hcks0hxX50NbLQdym1gekk8JTAoIfar0213Dw6q7EyrbjE+zjEp5gY8QNRYr46RrqcB9,iv:3wRg1C0Cnivx7Md3OnJrn12nBT3TsQUTmkBnKy4ZlRg=,tag:uzKsVdPMoSznCfyHFY2qbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d3l0vzqtufh5dfy5f2aqh0zjmdxw3yhdk6ccvh39xxd8g97stq5qzst4kz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVXIrQXloVHowSXN2eDY0
            YlJuVmdyNTBFZDVYRENURHExVWdEcUJMaHhnCisxc3dzcTJmSmxWK3lzbU0zUmZM
            ZENrZno5Rk9hU1UxWDE2QmU3OGxEczAKLS0tIDlGQUlWNW9hUk4yS0RsQW83M0Zz
            bjkyS0lTVlFCWDMrNWNzUXV0MG9XREkKTXmZ8mEX5OjS+ynW1b7YgxLvPPNDsP8m
            doR3WeN+1biOydvN/amp3rfYMzC18jNSYqCQ3rPRJo4JaPfgOuwAtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T06:20:16Z"
    mac: ENC[AES256_GCM,data:rTy+JP0VORpwQlswO2RMkbRZNK3/2eHtrewVoMOSWFXD4ElojtVFJWXXzD6P4GBqOtRdJmBM7ev9+2K6mkzuwATXcPxCFmrXlPxt1EEQt1yiGTw91NWAFeB7GOWGPVrvUk6IX/5Sksjqd8WjM4E06FBPfwcM273vxv0Jef3/dq4=,iv:ekSqJEhcboJ9aGcgeV5WtjmEUuVbK2y7Gx6pHdUYxto=,tag:IdQp3kuQlAseyLpaSFSHgw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
