hosts:
    production:
        port: ENC[AES256_GCM,data:BeA=,iv:W4oS145gGLRjtHX3tALW/41JK3Tap4TRSGIWBst9SxA=,tag:GajS94h+AIht81w1mNoLqQ==,type:int]
        identity_file: ENC[AES256_GCM,data:+RYVyUENC+fdVo2pxJtAlBcuJA==,iv:Wmz2VTGD7dMyfTCFmgGrH5jxudv6iNL+ZNjd0GnRvrU=,tag:1OzPfNkG+2r9Fm0ykrZCkA==,type:str]
        forward_agent: ENC[AES256_GCM,data:a3bGDA==,iv:I41WM5/X4l/RA9YwxVDxNnVCLbhIsHlDNnzvm8J5C8k=,tag:pibA0n9kUe9Lik41bEXD6Q==,type:bool]
        keep_releases: ENC[AES256_GCM,data:dQ==,iv:IbF5T4wrWC79LNteffHhjSL6pvLMnqz3sr8iqI2NZyc=,tag:xA4zqbR5FrXr/T+yqrT+/Q==,type:int]
        git_ssh_command: ENC[AES256_GCM,data:Faek0u8d2JVfmiExxNjwxyTQiyyUEafAke4U2SOzKtscNhnBKBjB0YscRQpZHVjX1s/DJCN6mGnR7lUDlxIU,iv:0wmZXz+UoJoz0N7OuXn+iUdlOTp3azfMncxG2ZLE3vA=,tag:Q4rV9sfBItct9HOejShfuQ==,type:str]
        ssh_arguments:
            - ENC[AES256_GCM,data:5FoFOFnp4s++KFneMHB+m9vrA8On,iv:gYtsIJxozgOuDTEcoQFO8lGy50JSu6H+DTu845H8UeQ=,tag:JxauLsgV7s16sXoaOADLDw==,type:str]
            - ENC[AES256_GCM,data:ETzgiEoACu4efkRa1VpxFznuoIrGRh+hnJ/P7Z4THg==,iv:Ug/zRnge3P9y6JP9vy1AZFS8BDfZJMvRQOfaAWNOj38=,tag:F9omvmpWk8h/udl7jPZc1Q==,type:str]
            - ENC[AES256_GCM,data:+jWkZoxLrHtrLc4+NjtXUSBCaxwpVnvKUZuY,iv:K9s9fKnGWHrQRLsPve1Q0BEQCUqB6rI7JFC+FzgZyYk=,tag:IX63kl3vXMtkEOIubeMy0w==,type:str]
        bin/php: ENC[AES256_GCM,data:MeNAyV8eVNGizyOXqiCYZA==,iv:aEg7KLpOKNoxFTTsx7CWcQ/zvvJgKTuHE7s4w8d1WsM=,tag:CEmv9/pOOpFhxMUIImGtig==,type:str]
        hostname: ENC[AES256_GCM,data:sWrstb8hVaGPQcVCbMvW8bt1epOxHtRluw==,iv:2pICvdcsVp3c0R7lq8afGMwjc/lASCVAJw/gdmCtwB8=,tag:sFGnEmW13kxJB5GjpN2/tg==,type:str]
        remote_user: ENC[AES256_GCM,data:K+jmOXP6yI36mdKq,iv:aYkWaj/CaNy38GyHKs8kt8faBsbQ+iwtvB1RlDTUZEA=,tag:C44cxYl3w4+caFqNEypntQ==,type:str]
        deploy_path: ENC[AES256_GCM,data:f+rdiynxfTCWExUV7ZDS3QlucDXKoSEPy1IjGryc4+WKZXk=,iv:Q6PTXXOJI61wkjRg6ZYSNONGqD4UklEzCUEGTOpO+lw=,tag:K2Dg2ywVeyXkliPKZipNlA==,type:str]
        database_url: ENC[AES256_GCM,data:ULlkoflWVJO7c2/vIBDcSNsNY9unzBx4RXqj0jNDvVSY2HwTp96fslTw42ZKzp4vPnmOpOsVGDKhTYXo462EvybJe4kKnl+0Diqlb7BGfsCkD4PBmGO13mfSHpETVniFZxL8j/u8YOfRfC1CftknatBVigBx95OIf0M=,iv:366kRbmnzxwldwe7h9pGkQDwFRnZXk15YhR7GEpGDkw=,tag:SNLaCy3vqmWxija4MrbRwQ==,type:str]
        branch: ENC[AES256_GCM,data:ov+qKg==,iv:ba0D2aeXyjQgem4uxlznFsS1JRSSJph76/B2tsXC1qo=,tag:6XAv1r11rUWCK2pMY+RB1g==,type:str]
        app_env: ENC[AES256_GCM,data:NeXZzQ==,iv:8HrHsHyugmIPs735+98LNLduDPB4j0mGbqO1JV7F1M0=,tag:b+uU6ZhjQeuVO946HfdW5w==,type:str]
        brevo_user: ENC[AES256_GCM,data:UKHK0QlUHBpzSHCkqXpqrpSJjpDU+e/zUrY=,iv:yB/Nm31Wedc45jj9Q8XYuL7H4C8f0Ax/h3c8tVtBgR0=,tag:Tc55lCOB7VoVkC/hmumYzQ==,type:str]
        brevo_pass: ENC[AES256_GCM,data:l7swDRk5Vr3Msh1wL/GNY8GpHgsGq9kdMoJq9NCpWfTcMrcaM/I9JZ/U56wFg/VJ3iQiJroxDfQPq7DH98wQTj2T7XZafenEuf+6LrR/sGn+nGFHYnMWgts/,iv:FNoS3XbYr7ltg5Jx3Vhxd6Noi98SxcHLJ/r69rqvtnE=,tag:JjKbSMxJ7FggSPF6OcRV+w==,type:str]
    staging:
        port: ENC[AES256_GCM,data:JFQ=,iv:fM+2XabKEaHVxwmA66k8WGl8kFYUPB760aekRJJW3wE=,tag:+ev0l9HUnQabrswbNJZiQg==,type:int]
        identity_file: ENC[AES256_GCM,data:KKqFZKgsZAzNCWLPUEMjXAhrEw==,iv:0BmSa5nxkr9PqyKNgZEzF4Nwi9Kwduiw8HwLI4gH3eA=,tag:14si595Ku91Uuirhee4jsQ==,type:str]
        forward_agent: ENC[AES256_GCM,data:6K1LGw==,iv:uYgBkRpiFFq7Yyu2v8DlVbtxsYYQGkre4+dSz3/P6FI=,tag:6n2DhnzBF6nkGKv3PKyCGw==,type:bool]
        keep_releases: ENC[AES256_GCM,data:TQ==,iv:KpgcPWdfEH/aLZkmFmf4dp7k8Gdid8xLWlBAanoCGVc=,tag:XmKIXQ2kmNiJC8r9SrwA7A==,type:int]
        git_ssh_command: ENC[AES256_GCM,data:vM4n44RS44VDisODzWkHVwLESe4uJBhwiRbvL4ozIeraNCIK1iMbR8DeFyvz8Bz97nNUaeTkuKUnQBCbNyyV,iv:IZnHMqbN/Z+qbCaAtL1WB9XspyZO20qtndJMGjYgT1g=,tag:ADYm3znffiou42MVhQpZzQ==,type:str]
        ssh_arguments:
            - ENC[AES256_GCM,data:LJ3fqmTI9/Jh+CwJo+cvRY4rZZdY,iv:TubYDEwTK9Ce6fF02krww7oc0RfytL2+6gax+x/MvWg=,tag:JC9J555SBYgvn7yA5xDD8Q==,type:str]
            - ENC[AES256_GCM,data:NBkIgfrqfnaYa4DOupShjdPEvNXcVMhCTUIxeI9hqg==,iv:2XwO1Ho+9Wp744GDloDrnEEUxJBsri/FrzyeFw/kT4U=,tag:QL4ZJ7tIaO1dL+R9QLxHqg==,type:str]
            - ENC[AES256_GCM,data:ZDVSTRWE5AOkpqZ34POZjHOm/niejtn7K/SL,iv:Jw3Md/Vy4O2+HqIJ1e3MYANU1HNIwxYCyDBiWhoWilU=,tag:UbUhQfRzpBDHgEe4vE9bdg==,type:str]
        bin/php: ENC[AES256_GCM,data:G0eoZ2FsQR2aMFRjtW7Jkg==,iv:VXJr0Kom2A5ft+tEJY39Rtzsv9+5LQOnEYPOGlMvU8Q=,tag:M0siYe8coJOkVB3qZxycUw==,type:str]
        hostname: ENC[AES256_GCM,data:A5EkMB52zneIh0i+f370aJVfJ2TT9KSvng==,iv:7RTK14nNej3yMsORjHvewVyx8VFm8vWxpS6QN6mZFis=,tag:YXNGSLz0aa6XV34KRAZaCA==,type:str]
        remote_user: ENC[AES256_GCM,data:4kFN6imuIVzWFCqe,iv:hTw44D6d4QHvImNq6cF94E6Gtx1gRUwFYOpMCe7mYQY=,tag:7At/51WWOIb8/OSZ4nqn9g==,type:str]
        deploy_path: ENC[AES256_GCM,data:EThqwSE6WRVFei6GpVqaUS9QSAjxmmq1A7pHxkeVIFaUvdvDcW33,iv:tip63Xki/pcB0ySuAPA6MivP6yNg0nvMVzYvSr9b3Wo=,tag:xdwp205MYpXrbnVyZXI7ug==,type:str]
        database_url: ENC[AES256_GCM,data:tnj0ZWu/TMy0Zn/t5IpxrE9EQrRaDepqnVp17HmmW3BGE4o6zPcwljOvwMrYnhvpPSM/r8unhUnjiP6Hx+Ur//qzAOf1o1k7Bqkw9lm1Ni2ZmYleg8Hl3RixSN4BRtHgyAy5lIX6H5Q/UH+YQGWj/DWjOFDfNqFfKt/1jJMYTVWYuA==,iv:2Y7/395JrDHTnBY2xHxMq+Nn8nk8RzmHPQF5T7cvZq4=,tag:mCKnnTLO6vEINNzQpOPa7Q==,type:str]
        branch: ENC[AES256_GCM,data:00Of+H/dZA==,iv:JHlniC62b97jgYOqdjEI4HwsO3kTmaB7PGTTIi4ruU8=,tag:LFhaRJ4rggpu44mQXBgeJg==,type:str]
        app_env: ENC[AES256_GCM,data:Xs2FM+IgSg==,iv:CY0+igh5xRoA/udl64ryOCBysWoXXrtJhlnEdTlMphk=,tag:Ndp28hS5u2I3UmKcUaQ/4w==,type:str]
        brevo_user: ENC[AES256_GCM,data:kRG1NYpR/leL73sYbW/k+2ROzjVvQ7vZlHQ=,iv:HussDx4dX8xPhIS5UOpD5xi1FTB/C57I/P19d15vsj4=,tag:Y+7iM6NW+PyPm78JWBRnDw==,type:str]
        brevo_pass: ENC[AES256_GCM,data:FiqIG1bDqiEqfqqkeHZImUksfYjSVY724Sg1Tj+V3KGnLOdPytbhU5lu2xq1bNs+FpNgoh3M1pPxEEDgSAk72PqfnGgk5oDzWBFo9DJ6giXpLZdtHeuhraan,iv:LmZFpXfuNdvsWGgdtoLsLKt2IvoWO+KVYwjNYzqNSx0=,tag:wR2ZkTV9mwIjG4myo21USQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d3l0vzqtufh5dfy5f2aqh0zjmdxw3yhdk6ccvh39xxd8g97stq5qzst4kz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWDBGTjlxcWxvS0k4VmZ2
            TkVqRnBVaVllRUpCdmN6WlZPSW42emRobkFFCkplWVJRMklXUXdHWWJ4UCtLR3Bi
            ZFcxdDEyZUUyNFJhSmNONVFpcWoram8KLS0tIHZSM3l0MDV2V1dXbms2bWJtWVRx
            OGFQem5xWGdFU0RyKzZBT0xSdG0wMUEKpfnkSl5QXb+m1uJDtDIHORMQsrTVlWcn
            My8ZwycCWtYjUBhBiUKm50uAV6Qn4yXJ4u7t7gfPLGOnS1gkDCHPQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-08T08:00:50Z"
    mac: ENC[AES256_GCM,data:7X3dh1zS6+gwW3FdpXXf/9Ofdsf50wChEFvOMX7aH/oQezB90FCaEihewbJuwRWrceoQngXC/VXTbx7cct9Tr+/nNS3PxXZXloNMZA5aBqnRmBJp6oYM6rlKCSSgP++zQ1zGUkqEsmEHzEaaK6KnngTnog580X/5kazJGZ8etZs=,iv:TKAqk60+ImgzNdCT8ySXDUBW4+pcwIkNyN44z4IaRio=,tag:QfmveLGCOOmbWQ56o9MZnw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
