hosts:
    production:
        port: ENC[AES256_GCM,data:f6k=,iv:+XOBTH2rfEyvmBJMKSvLnCrPeL7RVBhrG8OA/jdH2Po=,tag:b6NtzyDJwlDYWWW5HbE2rQ==,type:int]
        identity_file: ENC[AES256_GCM,data:taBA6UR2mye0bygxhJGAOtNwVw==,iv:u4VKczeABp6ZlmdkD1yUhunEYhaYnrYwjZSC7iwV37o=,tag:bAu26G4GclveijzsV5Uzrg==,type:str]
        forward_agent: ENC[AES256_GCM,data:sY27Tg==,iv:qLttEmFkY0C23Wqk1mIMHtbidVmu6vRCFpmnEZjMCAM=,tag:jBaaQaJy4Zi8IgMsXvj/GQ==,type:bool]
        keep_releases: ENC[AES256_GCM,data:Xg==,iv:xgEf6YX8WNyamuQ02q7v3rqE7d7BpfCnW+y1TE5gmno=,tag:5NTdOXQB+nsQLS8ua7hOyA==,type:int]
        git_ssh_command: ENC[AES256_GCM,data:5kL6LebZO/m7/Yog0BTwz8ntHvaXsN/kn4LjaPJ84B2GlIp/CcJEfx9KeA8w3V9g3QBPLZFY5/RPquKvQRGa,iv:2BLeWz5fBtJTe3nih62BtZ/Ins+qr45f/SqkeLjYvVo=,tag:7tBk85R2aineyshuenwWGw==,type:str]
        ssh_arguments:
            - ENC[AES256_GCM,data:NV/llfheqVIyLZSpiz61zlO9Dtob,iv:wkXcPBiTcNGzJkFj/XIntco0ogoQ/UrnIieQCYUXVlU=,tag:03VNRuEntbZ8OQy/BayYEw==,type:str]
            - ENC[AES256_GCM,data:KSnAVZQY27muFOW8CYkVWdDwE9X7nSFMqwC31/PssA==,iv:pIMlBIZb6mF4SuFEwygUzwgHLwuTTu+xMdSVeYY5aRY=,tag:UY+THsMi0GOO7hFty3lucw==,type:str]
            - ENC[AES256_GCM,data:xWcf0N9d+WYkFlkhNd53rh4fcipFUrf4xOgf,iv:a/c6txvLPKUqfWD2Y75qMAR+pZ4YO4bmQM13L8essoY=,tag:OnguHmy8dsXl5t5231UN6Q==,type:str]
        bin/php: ENC[AES256_GCM,data:tBHfO28p6yJ4UVn0XefpQA==,iv:zteYlrgCuBa3mC3bpAkrA8+5MSUYdDbRspjudbNoLUI=,tag:X7fQCSghxkqv+uRjUzKC5w==,type:str]
        hostname: ENC[AES256_GCM,data:FidoMvBByVof2gPFV21QdoV3TD1+u54VzA==,iv:5qnIJVY9L3yFnVUDLsSNNs3fYck9Qa5nZlMKMsVu/Dg=,tag:T1EIzol+QugqEEHcr3hJag==,type:str]
        remote_user: ENC[AES256_GCM,data:rProM+l0KunN/PBe,iv:l0ef6rCiks/nJdq4ENYZcyb5G+x0uohz5Da3L0chcCs=,tag:bpWsaVziqQ4y+k9hE+temg==,type:str]
        deploy_path: ENC[AES256_GCM,data:EzUVoBtjYqFfXPGeXvnoS6YGPrl1P6YqTS6cAQ==,iv:N3+uKEI5PAXfdB9slgZpGkmjISM1CYH9FJOy5zVWhVo=,tag:QA34KY3zP/9SEoicsUhY8w==,type:str]
        database_url: ENC[AES256_GCM,data:5u4piQkVedKrSyUzdBQ6xW0jGJyL8UCv5P2KP1slnxin+NffVFzavXqla6MD1ZEULMr1/d4IMIduIAMLau0WPcV77r/JnDOwYuiHU40ClwePjNeoPI0KD//oUnWoCDAGpUcqShOQnn5nzrd9n0EwfvWYdiklUkjCtDU=,iv:OoOWCz8R7raeVEWXO2n1LKr9PL4x4PAZfyy/xJrz45Q=,tag:RKysOQlwir2t9EO94f0zgg==,type:str]
        branch: ENC[AES256_GCM,data:dStMPw==,iv:hh6uXasjhjhyIRQx9hz37PiXMGRWqER9Brk2+oZgiAI=,tag:f1CmJFtojBBjbaIXYmlfhQ==,type:str]
        app_env: ENC[AES256_GCM,data:Br1CjYQ/6Q==,iv:MCNtYJkexGW65d5QODEKy3MUhfQalg0XlA/HPl3g/aQ=,tag:kPGE2x5cn//nm2JL7oOI2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d3l0vzqtufh5dfy5f2aqh0zjmdxw3yhdk6ccvh39xxd8g97stq5qzst4kz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVDA5NVl5alFMYmRla2ZX
            U1lGMWdKdEt1bSt6VVVJZlVoZGZvTTlZbEhvClRqZkJuWkNEa2xvYzBTR2RVai9F
            Qk5Yd0lDd1NYRWppVFI1OUJUOExxbXcKLS0tIHBuQzdqSHRKdVVuMWFKZjhEeksv
            MDNBUDZBSkhDUmI3SmIzWk9PWkd0SG8K9+8OW2WQ9+NnB+NKDur/A2NqwlOaVobY
            N5J1YuvrMMjwmTGu8uA/EjcBDWkySeAXX2mLoqNnF1ehOe3FS6S9fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-08T13:44:00Z"
    mac: ENC[AES256_GCM,data:G55kFndY/8t3k0vHqVPaKcp+4j2y/sOPOZLL3DWpbHxk2XxKDM1/6GR75DFATzN+WGdMPFjOvGQlHt7QSA58NSYbj4YEvQk1YXNlMLGFUhyJr/QerzHfi6OvTYuJRiVjP4t+XLcp559KI+VE5aT3PmlV+G/HX8E7f2OIgkdDeZA=,iv:+MmatoMGHTC551aLkf0YTGASKW2Y5ZGZo89NDriToac=,tag:fiZAO5qnOXOPCaWXEUMCAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
