hosts:
    production:
        port: ENC[AES256_GCM,data:pgo=,iv:V+ZBcQr//nqxupWWWUwXyR9/6YTcMxz9QteW5tWgszQ=,tag:oGZQ9q+hN5S2oWZTzAlbpQ==,type:int]
        identity_file: ENC[AES256_GCM,data:hFnut92bBkJaEvc2s1tmxR2isQ==,iv:k8aRzVSjbbwGVZljvBR+Gl8toidnMUPe7wqbC3dKjwE=,tag:uY+SetcK896UT/wsRa8U2A==,type:str]
        forward_agent: ENC[AES256_GCM,data:OzuPOQ==,iv:sYP+7pMvCT5r09oMWepFgt/LNVLrzrT9BgVabpHoCcg=,tag:lj0yXY9kDObBRZe/3KvtNQ==,type:bool]
        keep_releases: ENC[AES256_GCM,data:kg==,iv:q+pWAxTFH/iznhxFoLPJ/ermhWUVS52r8O6puV4nM88=,tag:G1SnBNPkA2uFvVtrVLcXpw==,type:int]
        git_ssh_command: ENC[AES256_GCM,data:6Jun9ti8HrMcSHqYW0nNJaAaqTBfpJ2db02SUbtVg9tfJ6KZaimxC1WAyg/UhiKzJfTteatHHLdTFOYkWdb4,iv:sWHGo6g4OEIqgx5K6r0755Sp0oxZSC6LvF2ksnOxXaA=,tag:wYDBUk+9IA7NDF2aGPQGrA==,type:str]
        ssh_arguments:
            - ENC[AES256_GCM,data:ud9RtcnHt8YOPkyhM8B6MaGF+t9O,iv:IOqmhmEbZJH1yMCKBssQe2FCAlNXh+WEHUwUKafFybg=,tag:zNTKAGJxXWQNA9qGAdmf1w==,type:str]
            - ENC[AES256_GCM,data:iiwAiiVvgTw9qzUMjNvTZeslyLbapkhA6XgCKHucvg==,iv:i1V9wVqFjGm6CRj2jWVe2Yua1M/tC8DjYR4Q7ZYuZ9w=,tag:5SUBbSdhJLoRouP2H0ME3g==,type:str]
            - ENC[AES256_GCM,data:MDipSDS9q6ojWmMCq46w6S7rQSNG3LtCyYvh,iv:0tBdqYjOs0XHoZceJ2OdMYSVe33ohlNvpRxztigwpnw=,tag:WH4EutDyKQEEouZSwpWBzA==,type:str]
        bin/php: ENC[AES256_GCM,data:u+G3Xb6Do53DqZudvQvp3w==,iv:JTPzx1MEsQA5K1C0gXVHf13ArcLr3zIML/QEWBhL4tQ=,tag:ZcOjNWbEh/ebVLjA77nBrw==,type:str]
        hostname: ENC[AES256_GCM,data:dDc1m2PJOmb97y8Yz0Y4ORom1qkUY8vnXQ==,iv:4tpkqcZQcUyI0rmUmuCMHdVRVVyS4+72JlmsvWnKd08=,tag:ma/clZfCX8t9d3l3HizWkw==,type:str]
        remote_user: ENC[AES256_GCM,data:qlrlN2rPiSuaGkLA,iv:kFQvo/Avakaro4LZO+5vBKi+UVHcPOsvy2lNDIgAG70=,tag:E67g2S0GRFpO9RPZeITQ7A==,type:str]
        deploy_path: ENC[AES256_GCM,data:gj3Lvh8pBIAbAixtw2yM96k4og+7jrvN+TVj078N3tu9ADA=,iv:clXpk/0SFPAzvGTo8nf2NheRm3W1ib+E0NzolRmIzxE=,tag:Aiohe+lBhnCCPQ+3plZ7rw==,type:str]
        database_url: ENC[AES256_GCM,data:+SdKZ+bl6g5jBRlEhbv0zy8HzBd5J+zVfVhBgCV9xTF+vJNX7uis4rKtZQiJrQe6Mt+hBqLXOzHt9c0/+MNnwoOXKQM781MCYnNrPw1B078IBZjhuTi3w3sa51cjPS+jRwnjOTAKfr7bP5qLXkxiSFXKa6CrMkn+XyE=,iv:DOMuboe/hvrv/YoKV+riFq/9CJFQgNH7NgiKCRZvsqI=,tag:s54h0aHZFnG8Yy1U1HzLlQ==,type:str]
        branch: ENC[AES256_GCM,data:acm8MA==,iv:NERYP7vvOECZMoSDtEtBE2fguD4RP120Zx/twK43Qhs=,tag:CEbgATqsGdQnUxdgVQeI4g==,type:str]
        app_env: ENC[AES256_GCM,data:/TUuKA+HVg==,iv:M6A8rDcjZf3vYEx0bILeaqTClUnALNqQzJkgJshSNgQ=,tag:1IOzhwJoiVZeOnuSf7ZZwA==,type:str]
        brevo_user: ENC[AES256_GCM,data:a9pZ3IvLwnruMoQGSumFr8nvNx+hTfNmYvA=,iv:MGj0XC8nKgh8APc7+vh5GiXJtqVc6Kq9bkfv7VrWyJU=,tag:0XzcmJuvAqTG0vAk4EG22Q==,type:str]
        brevo_pass: ENC[AES256_GCM,data:XxVswW5GoClcaflw/E1OLESainKTwmv+ehG5m6TRcAKc/IYI/KlKi2Ggkb7N9HDiTDnQC51NsZD2TTFefsIzEuwIpqZyI7FpSLGOwHIuN5FlA/BAk7LShjUA,iv:cbm5cnJrTYlaInNO66Rw8wQjvU/j2NSdBMRBlluVETE=,tag:t//SlqBw0PHllaQXpOpVhA==,type:str]
    staging:
        port: ENC[AES256_GCM,data:EVw=,iv:0ySBz0lNW1XFMey6BmB1DvYG/TZaW5J4D6+JaHNF0BY=,tag:kdUbHr+kjbUlSB2AdKQ7pw==,type:int]
        identity_file: ENC[AES256_GCM,data:z5jnqcIggB1LDTz0TlGCI1ELmA==,iv:zdm/YdZq81mIryI40oEcUjPSVtpGKLLAm53WQwhRqfE=,tag:ggMUPd0RpWyPlndrWy3DWQ==,type:str]
        forward_agent: ENC[AES256_GCM,data:WlwpuA==,iv:wpwXD87aF+RMkiNBZYOjHYOP5Q+sm6zJUrxA7ysqbJI=,tag:HPBh5Bg8m8IkfptB4acxCw==,type:bool]
        keep_releases: ENC[AES256_GCM,data:1A==,iv:Iu4l2vGqPsEsHlWst4nYO4qbI+s+v2WLWyDfP2Gc5Ok=,tag:rhdB/H6FDQ2psFYdf7gWFg==,type:int]
        git_ssh_command: ENC[AES256_GCM,data:T2EWj4JBFiM2sQDoWUqQ3hlrferx0jTScVSIsb2PuvUiaYFaaxPO20xdmxosYXrgvSprbZTOSI1XTHJ4hQvy,iv:ZbQhln9mGfPlajYLDZ1+6EB0K5CLp+1iZiLRLKJ3jP0=,tag:Kdn4He7YTRi5OJOTeushMA==,type:str]
        ssh_arguments:
            - ENC[AES256_GCM,data:SPxqHH+3YVjJ+Z/N72a2e07kf80D,iv:2JlWmv1+/eZKyhVdp8/dLF9ZFl5IjoYowUJ952dDaio=,tag:lYbIRjXZWxJzgRdRKf/dIA==,type:str]
            - ENC[AES256_GCM,data:btlFHh9A6PZhn6uFifhF5P70exaCCsfy1s6UGSsnEg==,iv:zdNHIVYB0caqvjbkLp95xShNKHaWfgfDJv7NX4Wq65Y=,tag:nPLKNgQ/V6hxpTENNvpBPQ==,type:str]
            - ENC[AES256_GCM,data:BmTuMbwEo3G/wY1vdmG6YywSAaHHyvR2Lbi1,iv:N+sUmsd4AsTQGj5OagzTbL4KVkyc41rJNL3FCIa/Nno=,tag:yu/jMcerAuSLMgzwIRSWoQ==,type:str]
        bin/php: ENC[AES256_GCM,data:5hByFPNo6ULeqiHD8MJy3A==,iv:7ShYx0t9NHw8VB0ndigFhy5FHZbxwqxyY0Y8fK+tXsw=,tag:FCjduM5/JrHNJ7+0cB0nCQ==,type:str]
        hostname: ENC[AES256_GCM,data:JEVomYfr/Jn90h6lIpyCVoStbTfgGNWApQ==,iv:MK0v84DHG2kmq2d1+wCwt2Y4aqNsl6mIAcmtAWo0CMQ=,tag:0MC8zw29FpsFux8lI9zbVQ==,type:str]
        remote_user: ENC[AES256_GCM,data:8GQg38FCKgQQ41OR,iv:zNF2QOd9e6LNt3uGS3x/I5zEeXf9oECJQ1ynlSmxZ4w=,tag:zDAJIg7AfBNaQvpEyjZ0VQ==,type:str]
        deploy_path: ENC[AES256_GCM,data:r/CXUWwLgU2hvuUuicCXldVUxa/8OaDl4ynMvC+kybRrjJEj3Za1,iv:c0/JqoZPp29RoGbm7Q8UdajEzCt0ipUluNH3sKWcO5o=,tag:/5RfACI1Rxf1GSBJ/NcGCg==,type:str]
        database_url: ENC[AES256_GCM,data:4fToRhoGPHJlTihUFVaYyFt4xFV7SN5R/EzMN1tKIJrK0MFZrCnPueSi1At7HR71lhIXqU5JxxoFa0Ks0kflovsj0y9npZh1aoDeAvEmpoJsr60bDWLn0sT/Af+ybps/NU1TjCQqyngN7VC1vbD9mus1DEnjiaF9hE4gkPlmec1HFg==,iv:CIuiDlIbTORyGJ16IbeZiAYFmtXDriS10CbZdYRgSNw=,tag:SSJZOSh9piq5ouFf3h59Ug==,type:str]
        branch: ENC[AES256_GCM,data:3J6PievXUA==,iv:iZD7SEjVdFgkzN07gh6tnxFBxJgfx+ma6ZodR5lEtbc=,tag:1f4SGCj65dQ1zXtD7za5zg==,type:str]
        app_env: ENC[AES256_GCM,data:BZGK1IvDdQ==,iv:fIgWvpMRr7PgSpKMApLoJHeO4+j1JH3LK3NA5C4QagE=,tag:w5YFP04iG4cIQqH4fzXLew==,type:str]
        brevo_user: ENC[AES256_GCM,data:WvWvWmFwWMunT966ewikSdZPvsD03y4Ur9I=,iv:eGeFnNEhAvt7E+WEdikxBxLBCXCdL0TlHyWvmlYblrk=,tag:b2fGdDZmvoyiRB24GsxAlA==,type:str]
        brevo_pass: ENC[AES256_GCM,data:D9gWvbkXBeBAKIqeEsWyPGELGKnC2DOaEo664VCMKP4HFn7a8T3Uc6EoeVl498d9u5dWP9lun7fzjWx+OZlI4tY2iVpouC74V1v630xY1dhc+kXMSMUZ19mP,iv:qGk2A9fSS/ZXrljdtx54pdDgsf3bNRqRkdF9U2TsC4g=,tag:twbVAkxWn4/vaa8e2qYVGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d3l0vzqtufh5dfy5f2aqh0zjmdxw3yhdk6ccvh39xxd8g97stq5qzst4kz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeWhPQkF0TjFVUWl0dTVT
            NE5TNVJsY3RYVHVUUFhLQTJmL0ZIdzJhbGhnCjAwZDIzQk5qOFJXNWJianV1R0Z0
            R0hEam5IcmNQYXlaOEpEemZNMENPWHMKLS0tIE1IM3NLa2FUcXFPcW5jRVlCL0Q0
            Z3AvdXpDclVRWm9XWi9IcitPQllKTlkKqqnS0iWc/g/w6LELznb+xc0vTk/f2Dqp
            +6T4SefHiyASJjpPmDPglN3mqI2YXj8W17l5sxTLjEZcUX8EzycGeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T06:22:07Z"
    mac: ENC[AES256_GCM,data:O9iRWFHFmkFCczPQCg+BhrPRhXolYQ2rIzESF2VfvF+x9j4cEi1svacN1DzAmMkDYdRFy35KnlCNuptOrzdPERocedOCJTrkh5fia1eDX19FPkjgJ0IMWblkLvZXsX/kscdvfEADyFfgKIu+vnwwRVsSZwfVll3Gkk78HTfqJmg=,iv:CbvQC7E3Wzy+rXRJdIzfNM3HGCXcEQcVEc0tB7n+y5A=,tag:hvWvYOQ1gwTqkDk4iLSeRw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
