hosts:
    production:
        port: ENC[AES256_GCM,data:ERY=,iv:okuisGeLFmrMz4ZrMqhglf9b365aSim2HCuWNeZ+8OQ=,tag:eMStNCYboV9opn9QnrkdTA==,type:int]
        identity_file: ENC[AES256_GCM,data:RAa+uZqzaxrV5xS31I1dACTdlw==,iv:Ld+v7qpflSBjowLBqweu6W9UYwDXvN1dFxttOEsl37A=,tag:JfYTNhd17JQM9QJY6ZGX3g==,type:str]
        forward_agent: ENC[AES256_GCM,data:xXs53A==,iv:ESJMUpME8aa8aGrY58p3NeIvKCe8l9Xm/VwlhpsXXR0=,tag:XHwk6vbNMt8kK6GaFAnFmg==,type:bool]
        keep_releases: ENC[AES256_GCM,data:Dg==,iv:Lsgt37PdHGvTiUX2ISv9Sk07dq4F2U6exvk11vcwmGs=,tag:eoBEefhbm91gzqht6v7YwQ==,type:int]
        git_ssh_command: ENC[AES256_GCM,data:T2fiZYN4aTwO2ogKykZ4umXExcLBVBcCAku47Gs1NXuHbPp7h3OTPaH2a/iZD0WLyNEZ8rDV9tR6BpIu9io+,iv:P54a+DmysLihJJEiqD/xoUcCFndESPbEbKwz2sbrjDI=,tag:ODmfOoIswYRob9miXOjQfA==,type:str]
        ssh_arguments:
            - ENC[AES256_GCM,data:+u5qFdXP8zx4JnibzCd4I3YPi1uw,iv:dHWW2SdGNaCAWqMETjPhAw1tkXXm3JknfVewp/S8hUs=,tag:mDylhYXKCmnz3uKM4UFLwQ==,type:str]
            - ENC[AES256_GCM,data:YeiC03xdyfs9i5J8nFgAXcG2G5sKnuKavUDJIf40mA==,iv:QZ7Z4fTZn0VevKBQvkvLHlzL72thZq0sisTlbPVLpbI=,tag:MzWb3Jkl5NSU4uOM6O7kng==,type:str]
            - ENC[AES256_GCM,data:vRja1qha9h4viR3dPjhL8QVLPe0sy63ijrDP,iv:KeMa/3NwUOHigVauHwgbr+QruJYXI4Gh2/3PU6XewgI=,tag:KtRx/1IHl8RDEHpxAhOXgw==,type:str]
        bin/php: ENC[AES256_GCM,data:+ZxJVOnfx7zkR/OmHuC2iw==,iv:6NdHgxcSznSYXOKzUz/qVxFu5kRZh0kzIGWHpcY/7kc=,tag:HBu+CJZpAElGlVRJ5d0zKg==,type:str]
        hostname: ENC[AES256_GCM,data:hgkRel27GEhUjjcrXMVBT8n/5DtPRgLrkg==,iv:zxKH4FHQpdgJqbeom0biPcxxKgdvjon2zTHjJEUJN6M=,tag:UwngfdKNuWEApfJ+pYSJWw==,type:str]
        remote_user: ENC[AES256_GCM,data:8n9njXrvxjx7FqGE,iv:PzD4VzxS8+YYcI67Wa1XSQ4oU7CjxPJSM6bCw5BLb6A=,tag:4MWPTAGUPRsNYsRxyfTtCQ==,type:str]
        deploy_path: ENC[AES256_GCM,data:E5mNgBk85aKLu6qRcMpZDhIOlROlAuSOYMTQjeJYKXOFIU8=,iv:JnOiGXwr5lBUNtO7ow8fSZ1kFCgbw9wP4153doRtnrI=,tag:DllceRoU7751clRCD47GkA==,type:str]
        database_url: ENC[AES256_GCM,data:cgC7okIcAbszWLVS2Siil2LlzAYIBjMBw6sFAYNOzwO6KeDjYUs43WXqmILH3zS7ZdPCns5j7SqXZ8enKIWDNBE0/ApwxrZdsLtdIErGO0KDFCjr/HWKYqAkrBy2EyGsEAFIHpTaYO92nvSRowtr271wz7qljJ75GOo=,iv:bWrUOzEmdqYp/09LtGBWtIPbX/0Mv0pK3UYZj18azug=,tag:Jq1G8tJSqt9Wn+4GYWWO5Q==,type:str]
        branch: ENC[AES256_GCM,data:yNOsdw==,iv:Ps1UoVnigZt8mi4zhWv6VpMWG6FqIxG3iagFpJyfzMc=,tag:PtuNlxbei9Q0oXUVOdDwEw==,type:str]
        app_env: ENC[AES256_GCM,data:EO97etQpNA==,iv:15aTlfac4ThmTNzuAqJbj5rff+34qyVI9cb4emKW/1A=,tag:wEkIIwCYPqko3G3y3hDR1g==,type:str]
        brevo_user: ENC[AES256_GCM,data:yP6s96V/rUB2EXCT3xCtQo4QNdTpLwzXQ7ysfNg=,iv:CgyPxKjX63W0tNrIeS1+sm3cDMEXTAWQqrMvR6AZyYY=,tag:i08AIn7iYJHzUGKLd2E5Wg==,type:str]
        brevo_pass: ENC[AES256_GCM,data:f4wlESEcJFnFFakzr6vSKg==,iv:s/vZUtoJbRrR3eV1BU0v5gz1qWDPlTfihbv7oBdscH4=,tag:3nmxlOZ3UJ+k0HnfBwe5ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d3l0vzqtufh5dfy5f2aqh0zjmdxw3yhdk6ccvh39xxd8g97stq5qzst4kz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTjZUeHo3QjdCMnY4S2Fo
            Nnp4eExzZXBPU3dLZGdEYjBzQUNlZWJYclVBClJaVFpLZlAvMVhZUGZ5QUp6MWdM
            S2t4elREZ0daSFRvamtQclRyajJ1SEkKLS0tIEMvYUJ1bzBkZ3crY1JXTkgzM09E
            WitLY1dwV20vd3oxS1pyTEdVRFVhaDQK2/w1DXaxry22aFXa3C8wyrcd3uTpjoNr
            QlLdJVEvee+Zl+r3WE3Gz/Num7vFj74zd64GLyhneig2BMvh6pzteg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-09T09:54:22Z"
    mac: ENC[AES256_GCM,data:BWh9y6QP4F0i0ntNnPdoHZLI8Lfzof0jbLeXAvNGCflgtYDkd8k+c3DoC40ndljOEU/92KXtTB9Crp+qTLV+KArCrhrqkkOdvFCUo4+aPcSYq0hweaUuGeJ7G3RWpiq1iZS0cBs9atMMdpl51IKGhcnP3PZvT6L1Z7La+PGCtlA=,iv:DqtaJzYg61SHK9aQcl21iIoZYg2AVMF0gWDJiVwy9LA=,tag:gw9PI0iT7e2GSfpApIfc+Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
